---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: releases.helm.sh
spec:
  group: helm.sh
  version: v1beta1
  scope: Namespaced
  names:
    plural: releases
    singular: release
    kind: Release
    shortNames:
    - rel
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: manifests.helm.sh
spec:
  group: helm.sh
  version: v1beta1
  scope: Namespaced
  names:
    plural: manifests
    singular: manifest
    kind: Manifest
    shortNames:
    - man
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: values.helm.sh
spec:
  group: helm.sh
  version: v1beta1
  scope: Namespaced
  names:
    plural: values
    singular: values
    kind: Values
    shortNames:
    - val
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: lifecycles.helm.sh
spec:
  group: helm.sh
  version: v1beta1
  scope: Cluster
  names:
    plural: lifecycles
    singular: lifecycle
    kind: Lifecycle
    shortNames:
    - life
